@baseUrl = http://localhost:3333

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Luiz Gabriel de Oliveira Nazario",
  "email": "gabrielnz2006@gmail.com",
  "password": "?Teste?6689"
}

###

# @name get_all_accounts

GET {{baseUrl}}/accounts

###

# @name authenticate

POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "name": "Luiz Gabriel de Oliveira Nazario",
  "password": "?Teste?6689"
}
